services:
  infra:
    build:
      context: ./infra
      dockerfile: Dockerfile
    volumes:
      - ./infra/opentofu:/infra
      - ./infra/.sops.yaml:/infra/.sops.yaml:ro
      - ./infra/secrets.sops.yaml:/infra/secrets.sops.yaml:ro
    secrets:
      - age_key

secrets:
  age_key:
    file: ${AGE_KEY_FILE:-~/.config/sops/age/keys.txt}
